#%RAML 1.0
title: Test Test
version: v1
baseUri: /{version}
protocols: [HTTP, HTTPS]
types:
  User: !include types/User.raml
/users:
  get:
    description: Get a list of all users
    responses:
      200:
        body:
          application/json:
            type: User[]
            example: !include examples/Users.json
  post:
    description: Create a user
    body:
      application/json:
        type: User
    responses:
      201:
        body:
          application/json:
            type: User
            example: !include examples/User.json
  /{userId}:
    get:
      description: Get an instance of user based on it's id.
      responses:
        200:
          body:
            application/json:
              type: User
              example: !include examples/User.json
    put:
      description: Update an instance of user.
      body:
        application/json:
          type: User
      responses:
        200:
          body:
            application/json:
              type: User
              example: !include examples/User.json
    delete:
      description: Delete an instance of user based on it's id.
      responses:
        204:
